### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by hilbertletanger** [realAaronRan/OGM_radar#1]
dear AaronRan,
recently i am working on radar occupancy gridmap and i found your project might be so useful for my further paper implementation, but i have some trouble understand the data structure used in this project. so could you please commit an example of data on which i can run your project and then understand what data you accessed? I will thank you very much for doing this for me.

sincerely

**Comment by realAaronRan** [comment]
hi hilbertletanger,
sorry, I can not give you the entire raw data, as i mentioned in README that this project was supported by my internship company, and i did promise them to keep them data safe. 
But I can give you some data to show the data structure I have accessed, as shown below.
![Uploading image.png…]()

frameCnt: frame count
ID: mmw radar id, in my project, the vehicle is equipped with 4 radars
NumPCloud: point cloud numbers, indicates how many points in a certain frame and a certain radar
SNR: sign-noise-rate
Vel_ms: dopper relative speed, not used

hope this will be helpful

**Comment by hilbertletanger** [comment]
so many thanks, it is enough for me to understand the data structure and then the gridmap method.


best regards
